In [18]:
import pandas as pd
df_csv = pd.read_csv(r'C:\Users\FRED\Desktop\FreeCodeCamp- Data Analyst BootCamp for Beginners\Pandas Reading Files\Company_data(edited).csv', index_col = "Name")
df_csv

,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,
Walmart,Retail,"648,125",6.00%,"2,100,000","Bentonville, Arkansas"
Amazon,Retail and cloud computing,"574,785",11.90%,"1,525,000","Seattle, Washington"
Apple,Electronics industry,"383,482",-2.80%,"161,000","Cupertino, California"
UnitedHealth Group,Healthcare,"371,622",14.60%,"440,000","Minnetonka, Minnesota"
Berkshire Hathaway,Conglomerate,"364,482",20.70%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...
TIAA,Financials,"45,735",11.80%,"16,023","New York City, New York"
CHS,Agriculture cooperative,"45,590",-4.60%,"10,609","Inver Grove Heights, Minnesota"
Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.50%,"34,100","New York City, New York"
Dow Chemical Company,Chemical industry,"44,622",-21.60%,"35,900","Midland, Michigan"
Best Buy,Retail,"43,452",-6.10%,"85,000","Richfield, Minnesota"

In [19]:
df_csv.reset_index(inplace =True)

In [20]:
df_csv

,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,Walmart,Retail,"648,125",6.00%,"2,100,000","Bentonville, Arkansas"
1,Amazon,Retail and cloud computing,"574,785",11.90%,"1,525,000","Seattle, Washington"
2,Apple,Electronics industry,"383,482",-2.80%,"161,000","Cupertino, California"
3,UnitedHealth Group,Healthcare,"371,622",14.60%,"440,000","Minnetonka, Minnesota"
4,Berkshire Hathaway,Conglomerate,"364,482",20.70%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...,...
95,TIAA,Financials,"45,735",11.80%,"16,023","New York City, New York"
96,CHS,Agriculture cooperative,"45,590",-4.60%,"10,609","Inver Grove Heights, Minnesota"
97,Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.50%,"34,100","New York City, New York"
98,Dow Chemical Company,Chemical industry,"44,622",-21.60%,"35,900","Midland, Michigan"
99,Best Buy,Retail,"43,452",-6.10%,"85,000","Richfield, Minnesota"

In [47]:
df_csv.set_index('Name', inplace = True)
df_csv

,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
Name,,,,,
Walmart,Retail,"648,125",6.00%,"2,100,000","Bentonville, Arkansas"
Amazon,Retail and cloud computing,"574,785",11.90%,"1,525,000","Seattle, Washington"
Apple,Electronics industry,"383,482",-2.80%,"161,000","Cupertino, California"
UnitedHealth Group,Healthcare,"371,622",14.60%,"440,000","Minnetonka, Minnesota"
Berkshire Hathaway,Conglomerate,"364,482",20.70%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...
TIAA,Financials,"45,735",11.80%,"16,023","New York City, New York"
CHS,Agriculture cooperative,"45,590",-4.60%,"10,609","Inver Grove Heights, Minnesota"
Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.50%,"34,100","New York City, New York"
Dow Chemical Company,Chemical industry,"44,622",-21.60%,"35,900","Midland, Michigan"
Best Buy,Retail,"43,452",-6.10%,"85,000","Richfield, Minnesota"

In [53]:
df_csv.reset_index(inplace = True)
df_csv

,level_0,index,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,0,0,Walmart,Retail,"648,125",6.00%,"2,100,000","Bentonville, Arkansas"
1,1,1,Amazon,Retail and cloud computing,"574,785",11.90%,"1,525,000","Seattle, Washington"
2,2,2,Apple,Electronics industry,"383,482",-2.80%,"161,000","Cupertino, California"
3,3,3,UnitedHealth Group,Healthcare,"371,622",14.60%,"440,000","Minnetonka, Minnesota"
4,4,4,Berkshire Hathaway,Conglomerate,"364,482",20.70%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...,...,...,...
95,95,95,TIAA,Financials,"45,735",11.80%,"16,023","New York City, New York"
96,96,96,CHS,Agriculture cooperative,"45,590",-4.60%,"10,609","Inver Grove Heights, Minnesota"
97,97,97,Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.50%,"34,100","New York City, New York"
98,98,98,Dow Chemical Company,Chemical industry,"44,622",-21.60%,"35,900","Midland, Michigan"
99,99,99,Best Buy,Retail,"43,452",-6.10%,"85,000","Richfield, Minnesota"

In [55]:
df_csv = df_csv.drop(columns=[col for col in df_csv.columns if col.startswith(('index', 'level_0'))])

In [56]:
df_csv

,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,Walmart,Retail,"648,125",6.00%,"2,100,000","Bentonville, Arkansas"
1,Amazon,Retail and cloud computing,"574,785",11.90%,"1,525,000","Seattle, Washington"
2,Apple,Electronics industry,"383,482",-2.80%,"161,000","Cupertino, California"
3,UnitedHealth Group,Healthcare,"371,622",14.60%,"440,000","Minnetonka, Minnesota"
4,Berkshire Hathaway,Conglomerate,"364,482",20.70%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...,...
95,TIAA,Financials,"45,735",11.80%,"16,023","New York City, New York"
96,CHS,Agriculture cooperative,"45,590",-4.60%,"10,609","Inver Grove Heights, Minnesota"
97,Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.50%,"34,100","New York City, New York"
98,Dow Chemical Company,Chemical industry,"44,622",-21.60%,"35,900","Midland, Michigan"
99,Best Buy,Retail,"43,452",-6.10%,"85,000","Richfield, Minnesota"

In [57]:
#Multi-indexing
df_csv.set_index(['Industry', 'Name'], inplace = True)
df_csv

,,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,Name,,,,
Retail,Walmart,"648,125",6.00%,"2,100,000","Bentonville, Arkansas"
Retail and cloud computing,Amazon,"574,785",11.90%,"1,525,000","Seattle, Washington"
Electronics industry,Apple,"383,482",-2.80%,"161,000","Cupertino, California"
Healthcare,UnitedHealth Group,"371,622",14.60%,"440,000","Minnetonka, Minnesota"
Conglomerate,Berkshire Hathaway,"364,482",20.70%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...
Financials,TIAA,"45,735",11.80%,"16,023","New York City, New York"
Agriculture cooperative,CHS,"45,590",-4.60%,"10,609","Inver Grove Heights, Minnesota"
Pharmaceutical industry,Bristol-Myers Squibb,"45,006",-2.50%,"34,100","New York City, New York"
Chemical industry,Dow Chemical Company,"44,622",-21.60%,"35,900","Midland, Michigan"
Retail,Best Buy,"43,452",-6.10%,"85,000","Richfield, Minnesota"

In [63]:
#change table option to display all rows
pd.set_option('display.max.rows', 100)

#sort by first index. If have duplicates then sort by second index
df_csv.sort_index(inplace= True )
df_csv

                                                                        Revenue (USD millions)  \
Industry                            Name
Aerospace and defense               Boeing                                              77,794
                                    Lockheed Martin                                     67,571
Agriculture cooperative             CHS                                                 45,590
Agriculture manufacturing           John Deere                                          61,251
Airline                             American Airlines                                   52,788
                                    Delta Air Lines                                     58,048
                                    United Airlines                                     53,717
Apparel                             Nike                                                51,217
Automotive and energy               Tesla                                               96,773
Automotive industry                 Ford Motor Company                                 176,191
                                    General Motors                                     171,842
Beverage                            Coca-Cola                                           45,754
                                    PepsiCo                                             91,471
Chemical industry                   Dow Chemical Company                                44,622
Conglomerate                        Berkshire Hathaway                                 364,482
                                    General Electric                                    67,954
                                    RTX Corporation                                     68,920
Conglomerate and telecommunications AT&T                                               122,428
Consumer products manufacturing     Procter & Gamble                                    82,006
Electronics industry                Apple                                              383,482
Energy trading                      World Kinect Corporation                            47,711
Financial                           American Express                                    67,364
                                    Nationwide Mutual Insurance Company                 54,609
Financial services                  JPMorgan Chase                                     239,425
Financials                          Bank of America                                    171,912
                                    Capital One Financial                               49,484
                                    Citigroup                                          156,820
                                    Fannie Mae                                         141,240
                                    Freddie Mac                                        108,050
                                    Goldman Sachs                                      108,418
                                    MetLife                                             66,905
                                    Morgan Stanley                                      96,194
                                    Prudential Financial                                53,979
                                    State Farm                                         104,199
                                    StoneX Group                                        60,856
                                    TIAA                                                45,735
                                    Wells Fargo                                        115,340
Food industry                       Archer Daniels Midland                              93,935
Food processing                     Performance Food Group                              53,355
                                    Tyson Foods                                         52,788
Food service                        Sysco                                               76,325
Health                              McKesson Corporation                               276,711
Health insurance                    Cigna                                              195,265
                                    Humana                                             106,374
Healthcare                          CVS Health                                         357,776
                                    Cardinal Health                                    205,012
                                    Centene                                            153,999
                                    Elevance Health                                    171,340
                                    HCA Healthcare                                      64,968
                                    UnitedHealth Group                                 371,622
Information Technology              TD Synnex                                           57,555
Insurance                           AIG                                                 46,802
                                    Allstate                                            57,094
                                    Liberty Mutual                                      52,612
                                    New York Life Insurance Company                     54,317
                                    Progressive Corporation                             62,109
Machinery                           Caterpillar                                         67,060
Media                               The Walt Disney Company                             88,898
Petroleum industry                  Chevron Corporation                                200,949
                                    ConocoPhillips                                      58,574
                                    Energy Transfer Partners                            78,586
                                    Enterprise Products                                 49,715
                                    ExxonMobil                                         344,582
                                    Marathon Petroleum                                 150,307
                                    Phillips 66                                        149,890
                                    Plains All American Pipeline                        48,712
                                    Valero Energy                                      139,001
Pharmaceutical industry             AbbVie                                              54,317
                                    Bristol-Myers Squibb                                45,006
                                    Johnson & Johnson                                   95,195
                                    Merck & Co.                                         60,115
                                    Pfizer                                              58,496
                                    Walgreens Boots Alliance                           139,081
Pharmacy wholesale                  Cencora                                            262,173
Retail                              Albertsons                                          77,650
                                    Best Buy                                            43,452
                                    Costco                                             242,290
                                    Kroger                                             150,039
                                    Lowe's                                              86,377
                                    Publix                                              57,534
                                    TJX                                                 49,936
                                    Target Corporation                                 107,412
                                    The Home Depot                                     152,669
                                    Walmart                                            648,125
Retail and cloud computing          Amazon                                             574,785
Technology                          Dell Technologies                                   88,425
                                    HP                                                  53,718
                                    Intel                                               54,228
                                    Meta Platforms                                     134,902
                                    Nvidia                                              60,922
                                    Oracle Corporation                                  49,954
Technology and cloud computing      Alphabet                                           307,394
                                    IBM                                                 61,860
                                    Microsoft                                          211,915
Telecom hardware manufacturing      Cisco                                               56,998
Telecommunications                  Charter Communications                              54,607
                                    Comcast                                            121,572
                                    Verizon Communications                             133,974
Transportation                      FedEx                                               90,155
                                    United Parcel Service                               90,958

                                                                        Revenue growth  \
Industry                            Name
Aerospace and defense               Boeing                                      16.80%
                                    Lockheed Martin                              2.40%
Agriculture cooperative             CHS                                         -4.60%
Agriculture manufacturing           John Deere                                  16.50%
Airline                             American Airlines                            7.80%
                                    Delta Air Lines                             14.80%
                                    United Airlines                             19.50%
Apparel                             Nike                                         9.60%
Automotive and energy               Tesla                                       18.80%
Automotive industry                 Ford Motor Company                          11.50%
                                    General Motors                               9.60%
Beverage                            Coca-Cola                                    6.40%
                                    PepsiCo                                      5.90%
Chemical industry                   Dow Chemical Company                       -21.60%
Conglomerate                        Berkshire Hathaway                          20.70%
                                    General Electric                           -11.20%
                                    RTX Corporation                              2.80%
Conglomerate and telecommunications AT&T                                         1.40%
Consumer products manufacturing     Procter & Gamble                             2.30%
Electronics industry                Apple                                       -2.80%
Energy trading                      World Kinect Corporation                   -19.20%
Financial                           American Express                            21.10%
                                    Nationwide Mutual Insurance Company          6.10%
Financial services                  JPMorgan Chase                              54.70%
Financials                          Bank of America                             49.40%
                                    Capital One Financial                       29.00%
                                    Citigroup                                   55.10%
                                    Fannie Mae                                  16.20%
                                    Freddie Mac                                 24.60%
                                    Goldman Sachs                               57.80%
                                    MetLife                                     -4.30%
                                    Morgan Stanley                              45.90%
                                    Prudential Financial                       -10.10%
                                    State Farm                                  16.60%
                                    StoneX Group                                -7.80%
                                    TIAA                                        11.80%
                                    Wells Fargo                                 39.20%
Food industry                       Archer Daniels Midland                      -7.50%
Food processing                     Performance Food Group                      13.10%
                                    Tyson Foods                                 -0.80%
Food service                        Sysco                                       11.20%
Health                              McKesson Corporation                         4.80%
Health insurance                    Cigna                                        8.20%
                                    Humana                                      14.50%
Healthcare                          CVS Health                                  10.90%
                                    Cardinal Health                             13.00%
                                    Centene                                      6.50%
                                    Elevance Health                              9.40%
                                    HCA Healthcare                               7.90%
                                    UnitedHealth Group                          14.60%
Information Technology              TD Synnex                                   -7.70%
Insurance                           AIG                                        -17.10%
                                    Allstate                                    11.10%
                                    Liberty Mutual                               5.30%
                                    New York Life Insurance Company             14.20%
                                    Progressive Corporation                     25.20%
Machinery                           Caterpillar                                 12.80%
Media                               The Walt Disney Company                      7.50%
Petroleum industry                  Chevron Corporation                        -18.40%
                                    ConocoPhillips                             -28.70%
                                    Energy Transfer Partners                   -12.60%
                                    Enterprise Products                        -14.60%
                                    ExxonMobil                                 -16.70%
                                    Marathon Petroleum                         -16.50%
                                    Phillips 66                                -14.70%
                                    Plains All American Pipeline               -15.10%
                                    Valero Energy                              -18.80%
Pharmaceutical industry             AbbVie                                      -6.40%
                                    Bristol-Myers Squibb                        -2.50%
                                    Johnson & Johnson                            0.30%
                                    Merck & Co.                                  1.40%
                                    Pfizer                                     -41.70%
                                    Walgreens Boots Alliance                     4.80%
Pharmacy wholesale                  Cencora                                      9.90%
Retail                              Albertsons                                   8.00%
                                    Best Buy                                    -6.10%
                                    Costco                                       6.80%
                                    Kroger                                      -3.60%
                                    Lowe's                                     -11.00%
                                    Publix                                       4.70%
                                    TJX                                          2.90%
                                    Target Corporation                          -1.60%
                                    The Home Depot                              -3.00%
                                    Walmart                                      6.00%
Retail and cloud computing          Amazon                                      11.90%
Technology                          Dell Technologies                          -13.60%
                                    HP                                         -14.50%
                                    Intel                                      -14.00%
                                    Meta Platforms                              15.70%
                                    Nvidia                                     125.90%
                                    Oracle Corporation                          17.70%
Technology and cloud computing      Alphabet                                     8.70%
                                    IBM                                        -16.30%
                                    Microsoft                                    6.90%
Telecom hardware manufacturing      Cisco                                       10.60%
Telecommunications                  Charter Communications                       1.10%
                                    Comcast                                      0.10%
                                    Verizon Communications                      -2.10%
Transportation                      FedEx                                       -3.60%
                                    United Parcel Service                       -9.30%

                                                                         Employees  \
Industry                            Name
Aerospace and defense               Boeing                                 171,000
                                    Lockheed Martin                        122,000
Agriculture cooperative             CHS                                     10,609
Agriculture manufacturing           John Deere                              82,956
Airline                             American Airlines                      132,100
                                    Delta Air Lines                        103,000
                                    United Airlines                        103,300
Apparel                             Nike                                    83,700
Automotive and energy               Tesla                                  140,473
Automotive industry                 Ford Motor Company                     177,000
                                    General Motors                         163,000
Beverage                            Coca-Cola                               79,100
                                    PepsiCo                                318,000
Chemical industry                   Dow Chemical Company                    35,900
Conglomerate                        Berkshire Hathaway                     396,500
                                    General Electric                       125,000

In [68]:
df_csv.sort_index(inplace = True, ascending = [False, False])
df_csv

                                                                        Revenue (USD millions)  \
Industry                            Name
Transportation                      United Parcel Service                               90,958
                                    FedEx                                               90,155
Telecommunications                  Verizon Communications                             133,974
                                    Comcast                                            121,572
                                    Charter Communications                              54,607
Telecom hardware manufacturing      Cisco                                               56,998
Technology and cloud computing      Microsoft                                          211,915
                                    IBM                                                 61,860
                                    Alphabet                                           307,394
Technology                          Oracle Corporation                                  49,954
                                    Nvidia                                              60,922
                                    Meta Platforms                                     134,902
                                    Intel                                               54,228
                                    HP                                                  53,718
                                    Dell Technologies                                   88,425
Retail and cloud computing          Amazon                                             574,785
Retail                              Walmart                                            648,125
                                    The Home Depot                                     152,669
                                    Target Corporation                                 107,412
                                    TJX                                                 49,936
                                    Publix                                              57,534
                                    Lowe's                                              86,377
                                    Kroger                                             150,039
                                    Costco                                             242,290
                                    Best Buy                                            43,452
                                    Albertsons                                          77,650
Pharmacy wholesale                  Cencora                                            262,173
Pharmaceutical industry             Walgreens Boots Alliance                           139,081
                                    Pfizer                                              58,496
                                    Merck & Co.                                         60,115
                                    Johnson & Johnson                                   95,195
                                    Bristol-Myers Squibb                                45,006
                                    AbbVie                                              54,317
Petroleum industry                  Valero Energy                                      139,001
                                    Plains All American Pipeline                        48,712
                                    Phillips 66                                        149,890
                                    Marathon Petroleum                                 150,307
                                    ExxonMobil                                         344,582
                                    Enterprise Products                                 49,715
                                    Energy Transfer Partners                            78,586
                                    ConocoPhillips                                      58,574
                                    Chevron Corporation                                200,949
Media                               The Walt Disney Company                             88,898
Machinery                           Caterpillar                                         67,060
Insurance                           Progressive Corporation                             62,109
                                    New York Life Insurance Company                     54,317
                                    Liberty Mutual                                      52,612
                                    Allstate                                            57,094
                                    AIG                                                 46,802
Information Technology              TD Synnex                                           57,555
Healthcare                          UnitedHealth Group                                 371,622
                                    HCA Healthcare                                      64,968
                                    Elevance Health                                    171,340
                                    Centene                                            153,999
                                    Cardinal Health                                    205,012
                                    CVS Health                                         357,776
Health insurance                    Humana                                             106,374
                                    Cigna                                              195,265
Health                              McKesson Corporation                               276,711
Food service                        Sysco                                               76,325
Food processing                     Tyson Foods                                         52,788
                                    Performance Food Group                              53,355
Food industry                       Archer Daniels Midland                              93,935
Financials                          Wells Fargo                                        115,340
                                    TIAA                                                45,735
                                    StoneX Group                                        60,856
                                    State Farm                                         104,199
                                    Prudential Financial                                53,979
                                    Morgan Stanley                                      96,194
                                    MetLife                                             66,905
                                    Goldman Sachs                                      108,418
                                    Freddie Mac                                        108,050
                                    Fannie Mae                                         141,240
                                    Citigroup                                          156,820
                                    Capital One Financial                               49,484
                                    Bank of America                                    171,912
Financial services                  JPMorgan Chase                                     239,425
Financial                           Nationwide Mutual Insurance Company                 54,609
                                    American Express                                    67,364
Energy trading                      World Kinect Corporation                            47,711
Electronics industry                Apple                                              383,482
Consumer products manufacturing     Procter & Gamble                                    82,006
Conglomerate and telecommunications AT&T                                               122,428
Conglomerate                        RTX Corporation                                     68,920
                                    General Electric                                    67,954
                                    Berkshire Hathaway                                 364,482
Chemical industry                   Dow Chemical Company                                44,622
Beverage                            PepsiCo                                             91,471
                                    Coca-Cola                                           45,754
Automotive industry                 General Motors                                     171,842
                                    Ford Motor Company                                 176,191
Automotive and energy               Tesla                                               96,773
Apparel                             Nike                                                51,217
Airline                             United Airlines                                     53,717
                                    Delta Air Lines                                     58,048
                                    American Airlines                                   52,788
Agriculture manufacturing           John Deere                                          61,251
Agriculture cooperative             CHS                                                 45,590
Aerospace and defense               Lockheed Martin                                     67,571
                                    Boeing                                              77,794

                                                                        Revenue growth  \
Industry                            Name
Transportation                      United Parcel Service                       -9.30%
                                    FedEx                                       -3.60%
Telecommunications                  Verizon Communications                      -2.10%
                                    Comcast                                      0.10%
                                    Charter Communications                       1.10%
Telecom hardware manufacturing      Cisco                                       10.60%
Technology and cloud computing      Microsoft                                    6.90%
                                    IBM                                        -16.30%
                                    Alphabet                                     8.70%
Technology                          Oracle Corporation                          17.70%
                                    Nvidia                                     125.90%
                                    Meta Platforms                              15.70%
                                    Intel                                      -14.00%
                                    HP                                         -14.50%
                                    Dell Technologies                          -13.60%
Retail and cloud computing          Amazon                                      11.90%
Retail                              Walmart                                      6.00%
                                    The Home Depot                              -3.00%
                                    Target Corporation                          -1.60%
                                    TJX                                          2.90%
                                    Publix                                       4.70%
                                    Lowe's                                     -11.00%
                                    Kroger                                      -3.60%
                                    Costco                                       6.80%
                                    Best Buy                                    -6.10%
                                    Albertsons                                   8.00%
Pharmacy wholesale                  Cencora                                      9.90%
Pharmaceutical industry             Walgreens Boots Alliance                     4.80%
                                    Pfizer                                     -41.70%
                                    Merck & Co.                                  1.40%
                                    Johnson & Johnson                            0.30%
                                    Bristol-Myers Squibb                        -2.50%
                                    AbbVie                                      -6.40%
Petroleum industry                  Valero Energy                              -18.80%
                                    Plains All American Pipeline               -15.10%
                                    Phillips 66                                -14.70%
                                    Marathon Petroleum                         -16.50%
                                    ExxonMobil                                 -16.70%
                                    Enterprise Products                        -14.60%
                                    Energy Transfer Partners                   -12.60%
                                    ConocoPhillips                             -28.70%
                                    Chevron Corporation                        -18.40%
Media                               The Walt Disney Company                      7.50%
Machinery                           Caterpillar                                 12.80%
Insurance                           Progressive Corporation                     25.20%
                                    New York Life Insurance Company             14.20%
                                    Liberty Mutual                               5.30%
                                    Allstate                                    11.10%
                                    AIG                                        -17.10%
Information Technology              TD Synnex                                   -7.70%
Healthcare                          UnitedHealth Group                          14.60%
                                    HCA Healthcare                               7.90%
                                    Elevance Health                              9.40%
                                    Centene                                      6.50%
                                    Cardinal Health                             13.00%
                                    CVS Health                                  10.90%
Health insurance                    Humana                                      14.50%
                                    Cigna                                        8.20%
Health                              McKesson Corporation                         4.80%
Food service                        Sysco                                       11.20%
Food processing                     Tyson Foods                                 -0.80%
                                    Performance Food Group                      13.10%
Food industry                       Archer Daniels Midland                      -7.50%
Financials                          Wells Fargo                                 39.20%
                                    TIAA                                        11.80%
                                    StoneX Group                                -7.80%
                                    State Farm                                  16.60%
                                    Prudential Financial                       -10.10%
                                    Morgan Stanley                              45.90%
                                    MetLife                                     -4.30%
                                    Goldman Sachs                               57.80%
                                    Freddie Mac                                 24.60%
                                    Fannie Mae                                  16.20%
                                    Citigroup                                   55.10%
                                    Capital One Financial                       29.00%
                                    Bank of America                             49.40%
Financial services                  JPMorgan Chase                              54.70%
Financial                           Nationwide Mutual Insurance Company          6.10%
                                    American Express                            21.10%
Energy trading                      World Kinect Corporation                   -19.20%
Electronics industry                Apple                                       -2.80%
Consumer products manufacturing     Procter & Gamble                             2.30%
Conglomerate and telecommunications AT&T                                         1.40%
Conglomerate                        RTX Corporation                              2.80%
                                    General Electric                           -11.20%
                                    Berkshire Hathaway                          20.70%
Chemical industry                   Dow Chemical Company                       -21.60%
Beverage                            PepsiCo                                      5.90%
                                    Coca-Cola                                    6.40%
Automotive industry                 General Motors                               9.60%
                                    Ford Motor Company                          11.50%
Automotive and energy               Tesla                                       18.80%
Apparel                             Nike                                         9.60%
Airline                             United Airlines                             19.50%
                                    Delta Air Lines                             14.80%
                                    American Airlines                            7.80%
Agriculture manufacturing           John Deere                                  16.50%
Agriculture cooperative             CHS                                         -4.60%
Aerospace and defense               Lockheed Martin                              2.40%
                                    Boeing                                      16.80%

                                                                         Employees  \
Industry                            Name
Transportation                      United Parcel Service                  382,550
                                    FedEx                                  446,400
Telecommunications                  Verizon Communications                 105,400
                                    Comcast                                186,000
                                    Charter Communications                 101,100
Telecom hardware manufacturing      Cisco                                   84,900
Technology and cloud computing      Microsoft                              221,000
                                    IBM                                    296,600
                                    Alphabet                               182,502
Technology                          Oracle Corporation                     164,000
                                    Nvidia                                  29,600
                                    Meta Platforms                          67,317
                                    Intel                                  124,800
                                    HP                                      58,000
                                    Dell Technologies                      120,000
Retail and cloud computing          Amazon                               1,525,000

In [88]:
df_csv.iloc[3, 3]

'Philadelphia, Pennsylvania'

In [83]:
df_csv.loc['Telecommunications', 'Comcast']

Revenue (USD millions)                       121,572
Revenue growth                                 0.10%
Employees                                    186,000
Headquarters              Philadelphia, Pennsylvania
Name: (Telecommunications, Comcast), dtype: object